# Generated by Django 5.1.1 on 2024-11-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_role_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
