# Generated by Django 5.1.1 on 2024-12-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_role_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderCustomer',
        ),
        migrations.RenameModel(
            old_name='Invoice',
            new_name='SalesInvoice',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employeeName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='roleName',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='statusName',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supplierName',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ordercustomer'),
        ),
        migrations.CreateModel(
            name='OrderSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderSupllier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ordersupplier'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ordersupplier')),
            ],
        ),
    ]
