# Generated by Django 5.1.1 on 2024-12-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_order_ordercustomer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeName',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderCustomer',
            new_name='order_customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderSupllier',
            new_name='order_supllier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roleName',
            new_name='role_name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='statusName',
            new_name='status_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplierName',
            new_name='supplier_name',
        ),
    ]
