# Generated by Django 5.1.1 on 2024-12-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_categoryname_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ordersupplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordercustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
