# Generated by Django 5.1.1 on 2024-12-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchaseitem_salesitem_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='order_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='api.ordersupplier'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='order_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='api.ordercustomer'),
        ),
    ]
